# Generated by Django 3.1.7 on 2021-09-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simplecourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='simplecourse.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, verbose_name='COURSE TITLE')),
                ('course_date_created', models.DateTimeField(auto_now_add=True)),
                ('course_image', models.ImageField(upload_to=simplecourse.models.user_directory_path)),
                ('course_description', models.CharField(max_length=400)),
                ('course_duration', models.IntegerField()),
                ('course_discount', models.IntegerField()),
                ('course_price', models.IntegerField(default=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
