# Generated by Django 3.1.7 on 2021-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecourse', '0002_auto_20210731_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=100),
        ),
    ]
